# 开发环境配置
server:
    port: 8090
    address: 127.0.0.1


mysql:
    database: Traceability
    host: 127.0.0.1
    port: 3306
    username: root
    password: a625391084.
    charset: utf8mb4

redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0
    pool_size: 30
    min_idle_conns: 5
    idle_timeout: 300s

# JWT配置
Jwt:
    Secret: "config_520_vv"
    ExpireTime: 24
    NotBefore: 0
#zap日志管理
Logs:
    Dir: ./logs
    Layout: "2006-01-02 15:04:05"