definitions:
  revo.AuditProcessRequest:
    properties:
      status:
        enum:
        - 1
        - 2
        type: integer
    required:
    - status
    type: object
  revo.Contact:
    properties:
      email:
        description: 电子邮箱
        type: string
      name:
        description: 联系人姓名
        type: string
      phone:
        description: 联系电话
        type: string
    type: object
  revo.LoginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  revo.RegisterRequest:
    properties:
      confirm:
        description: 确认密码
        type: string
      contact_info:
        $ref: '#/definitions/revo.Contact'
        description: 联系信息
      password:
        description: 密码
        maxLength: 50
        minLength: 8
        type: string
      user_type:
        description: 用户类型
        enum:
        - factory
        - dealer
        - supervision
        - consumer
        - admin
        type: string
      username:
        description: 用户名
        maxLength: 50
        minLength: 5
        type: string
    required:
    - confirm
    - contact_info
    - password
    - user_type
    - username
    type: object
  revo.UserTypeRequest:
    properties:
      request_type:
        enum:
        - factory
        - dealer
        - supervision
        - consumer
        type: string
    required:
    - request_type
    type: object
  utils.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回数据
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
  description: 冷冻品溯源系统API接口文档
  title: 冷冻品溯源系统
  version: "1.0"
paths:
  /admin/{log_id}:
    put:
      description: 管理员处理用户申请
      parameters:
      - description: 申请记录ID
        in: path
        name: log_id
        required: true
        type: string
      - description: 审核请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/revo.AuditProcessRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      security:
      - ApiKeyAuth: []
      summary: 处理审核请求
      tags:
      - 管理员管理
  /admin/pending:
    get:
      description: 管理员获取所有未处理的申请
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      security:
      - ApiKeyAuth: []
      summary: 获取待审核请求
      tags:
      - 管理员管理
  /admin/product/{log_id}:
    put:
      description: 管理员处理产品申请
      parameters:
      - description: 申请记录ID
        in: path
        name: log_id
        required: true
        type: string
      - description: 审核请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/revo.AuditProcessRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      security:
      - ApiKeyAuth: []
      summary: 处理审核产品请求
      tags:
      - 管理员管理
  /admin/users:
    get:
      description: 管理员获取用户列表（分页）
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 用户类型
        in: query
        name: user_type
        type: string
      - description: 状态
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      security:
      - ApiKeyAuth: []
      summary: 获取用户列表
      tags:
      - 管理员管理
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/revo.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户登录
      tags:
      - 用户管理
  /register:
    post:
      consumes:
      - application/json
      description: 新用户注册接口
      parameters:
      - description: 注册请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/revo.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户注册
      tags:
      - 用户管理
  /user/info:
    get:
      description: 获取当前登录用户信息
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - 用户管理
  /user/type-request:
    post:
      description: 普通用户提交用户类型变更申请
      parameters:
      - description: 变更请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/revo.UserTypeRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      security:
      - ApiKeyAuth: []
      summary: 提交用户类型变更
      tags:
      - 用户管理
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
